name: brio-summarizer
endpoints:
- respond_batch
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8169
      SERVICE_NAME: brio_summarizer
      PRETRAINED_MODEL_NAME: "Yale-LILY/brio-cnndm-uncased"
    context: ./services/brio_summarizer/
  command: flask run -h 0.0.0.0 -p 8169
  environment:
  - CUDA_VISIBLE_DEVICES=0
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 4G
      reservations:
        memory: 4G
  volumes:
  - ./services/brio_summarizer:/src
  - ./common:/src/common
  ports:
  - 8169:8169
proxy: null
