name: summarization-annotator
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8171
      SERVICE_NAME: summarization_annotator
      SUMMARIZATION_REQUEST_TIMEOUT: 10
    context: ./annotators/summarization_annotator/
  command: flask run -h 0.0.0.0 -p 8171
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
  volumes:
  - ./annotators/summarization_annotator:/src
  ports:
  - 8171:8171
proxy: null
