convert_based_nli:
- group: candidate_annotators
  connector:
    protocol: http
    timeout: 2.0
    url: http://convert-based-nli:8150/batch_model
  dialog_formatter: state_formatters.dp_formatters:convert_nli_hypotheses_annotator_formatter
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  state_manager_method: add_hypothesis_annotation_batch
