brio-summarizer:
- group: services
  connector:
    protocol: http
    timeout: 10.0
    url: http://brio-summarizer:8169/respond_batch
  dialog_formatter: state_formatters.dp_formatters:hypotheses_list
  response_formatter: state_formatters.dp_formatters:simple_formatter_service
  state_manager_method: add_hypothesis
